# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "1.18.2" ]
  pull_request:
    branches: [ "1.18.2" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3.3.0
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Pre-Build
      run: exit 0
#     - name: Validate Gradle wrapper
#       uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Delete temp files
      run: exit 0
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: Mod File
        # A file, directory or wildcard pattern that describes what to upload
        path: build/libs
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: warn
    - name: Upload a Build Artifact (Reobf)
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: reobfJar File
        # A file, directory or wildcard pattern that describes what to upload
        path: build/reobfJar
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: warn
    - name: Upload a Build Artifact (Source)
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: Resource File
        # A file, directory or wildcard pattern that describes what to upload
        path: build/resources
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: warn
#   publish_pre_release: 
#     runs-on: ubuntu-latest
#     steps: 
#     - name: Pre-Build
#       run: exit 0
#     - name: Set GitHub Token
#       run: export GITHUB_TOKEN=r4tA8ml2YNsQnZSl0ebec1VhDfhfcN01nHR6
#     - name: Auto Release
#       # You may pin to the exact commit or the version.
#       # uses: CupOfTea696/gh-action-auto-release@a8f57f49a805d334ac7abe31b689e7ea24e1ee40
#       uses: CupOfTea696/gh-action-auto-release@v1.0.2
#       with:
#         # Title for the release
#         title: Build Version $semver
#         # Name for the git tag
#         tag: $version
#         # Whether or not this release should be published as a draft
#         draft: false
#         # The path to the CHANGELOG
#         changelog: CHANGELOG.md
#         # String a CHANGELOG entry must contain to be used as the entry for this release
#         changelog-entry: $version
#     - name: Delete Temp Files
#       run: exit 0
