# 此工作流使用未经 GitHub 认证的操作。
# 它们由第三方提供，并受
# 单独的服务条款、隐私政策和支持
# 文档。

# GitHub 建议将操作固定到提交 SHA。
# 若要获取较新版本，需要更新 SHA。
# 还可以引用标记或分支，但该操作可能会更改而不发出警告。

name: Add comment
on:
  issues:
    
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'help-wanted'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue is available for anyone to work on. **Make sure to reference this issue in your pull request.** :sparkles: Thank you for your contribution! :sparkles:
  add-bug-comment:
      if: github.event.label.name == 'bug'
      runs-on: ubuntu-latest
      permissions:
        issues: write
      steps:
        - name: Add Bug comment
          uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
          with:
            issue-number: ${{ github.event.issue.number }}
            body: |
              Oh my god! It has a big bug! :sparkles:
