name: Issue Lock Handle

on:
  issues:
    types: [locked]
    
permissions:
  issues: write

jobs: 
  locked_handle: 
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
      - name: Unlock Issues
        # You may pin to the exact commit or the version.
        # uses: OSDKDev/unlock-issues@fe639fdd6c207b5b77dde7c1919a35475e3e3b81
        uses: OSDKDev/unlock-issues@v1.1.1
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            此issue已被锁定, 所以你不能发言。|
            This issue is locked, so you can't speak. |
            被锁定的原因可能是: |
            * 离题|
            * 垃圾问题|
            * 问题已被解决|
            * 问题**长期**不活跃|
            |
      - name: Lock Issues
        # You may pin to the exact commit or the version.
        # uses: OSDKDev/lock-issues@959e73072653cd29aea7c96622eec8a70599f240
        uses: OSDKDev/lock-issues@v1.1.1
